//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentisha.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Listing
    {
        public int Id { get; set; }

  

        [Required]
        [DisplayName("County:")]
      

        public string County { get; set; }

        [Required]
        [DisplayName("Town/Area")]
      
        public string Town { get; set; }


        [Required]
        
        public string Facilities { get; set; }


        [Required]
        [DisplayName("Number of Rooms ")]
        
        public int Rooms { get; set; }

        [Required]
        [DisplayName("Rent/Price")]
        public int Price { get; set; }

        [Required]
      
        [DisplayName("Property Name")]
        public string PropertyName { get; set; }

     
        [DisplayName("Property Type")]
        public string PropertyType { get; set; }

        public string Rent { get; set; }
    }
}
