//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentisha.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int PropertyId { get; set; }
        public string PropertyName { get; set; }
        public string County { get; set; }
        public string Town { get; set; }
        public int Price { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Amenities { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
