//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentisha.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;
    public partial class Property
    {
        public int PropertyId { get; set; }
        public string PropertyName { get; set; }
        public string County { get; set; }
        public string Town { get; set; }
        public int Price { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        [DisplayName("Upload file")]
        public string Image { get; set; }
        public string Amenities { get; set; }
        [ForeignKey("User")]
        public  int UserId { get; set; }
        public virtual User User { get; set; }

        public int Rooms { get; set; }

        public int Beds { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
